### ISSUE TITLE
Abstract fun cannot contain code

### ISSUE THREAD

**Issue by jkaan** [ZacSweers/moshi-sealed#12]
Hi! I'm not entirely sure this is related to this project since it is an KotlinPoet error, however probably you can still help :D.

I have code like this:

```
@JsonAdapter(generateAdapter = true, generator = "sealed:type")
sealed class Block() {
	abstract fun doSomething(): AnotherClass?
}

@JsonAdapter(generateAdapter = true)
internal data class ImplementationBlock() {
	override fun mapToDomain = ImplementationBlockAnotherClass()
}
```

When I want to map this, I get a KotlinPoet error saying 'abstract fun cannot contain code'

So it is most likely related to the `doSomething()` function but I couldn't figure out more. I actually read in the KotlinPoet repo that this should be possible to do.

**Comment by ZacSweers** [comment]
This should be fixed by a newer kotlinpoet-metadata version, sorry I missed this before. Is it still an issue?

**Comment by jkaan** [comment]
@ZacSweers No issue, I actually closed it since I haven't had this before. So it is fixed, yes :). Thanks!
