### ISSUE TITLE
Take class name per default

### ISSUE THREAD

**Issue by Globegitter** [ZacSweers/moshi-sealed#13]
What would be nice for the codegen if we could make the `TypeLabel` annotation optional and per default just take the class name itself. So if I have for example

```kotlin
@JsonClass(generateAdapter = true, generator = "sealed:type")
sealed class Message()

@JsonClass(generateAdapter = true)
data class Unsecure(val msg: String): Message()
```

that it would expect the key `type` to be `Unsecure` in this case. That would reduce the boilerplate and also is what I would be happy with 99% of the time. What do you think?

**Comment by ZacSweers** [comment]
I'd worry about casing for this. That said, I don't see why not if your type values are always also Upper camel case. Want to send a PR?

**Comment by ZacSweers** [comment]
Would rather keep it specific
