### ISSUE TITLE
code-gen for map

### ISSUE THREAD

**Issue by Globegitter** [ZacSweers/moshi-sealed#14]
I have a data classes as follows:

```kotlin
@JsonClass(generateAdapter = true)
data class Root(
    val id: String,
    val something: Something,
    val apps: Map<String, App>
)

@JsonClass(generateAdapter = true, generator = "sealed:apps")
sealed class App

@JsonClass(generateAdapter = true)
@TypeLabel("myApp")
data class MyApp(
    val b: Map<String, OtherDataClass>
) : App()
...
```

specifically where for `val apps: Map<String, App>` the key should be used as the label to choose in which of the data class the json can be converted to. Is that something that could be possible, without having to write my own adapter?

**Comment by ZacSweers** [comment]
Right now - no. Moshi-sealed works off of Moshi's polymorphic json adapter. That said, I do wonder if there's a space for allowing bringing your own polymorphic adapter somehow. I'm not sure what the API would look like, but it's a thought.

**Comment by trevjonez** [comment]
perhaps something generated here mixed with a json qualifier for those that need special treatment? https://github.com/square/moshi#alternate-type-adapters-with-jsonqualifier

**Comment by ZacSweers** [comment]
I think this is out of scope for supporting here. I think trevjonez has the right idea with a qualifier, you could work something where a custom adapter basically uses the readJsonValue() API and adds the key to the value map for the polymorphic adapter to read later.

```kotlin
// obtain a delegateAdapter JsonAdapter<App> somehow before this

fun fromJson(reader: JsonReader): Map<String, App> {
  val map = reader.readJsonValue() as Map<String, *>
  val resultMap = mutableMapOf<String, App>()
  for ((key, value) in map) {
    val valueCopy = (value as Map<String, *>).toMutableMap()
    valueCopy["apps"] = key
    resultMap[key] = delegateAdapter.fromJsonValue(valueCopy)
  }

  return resultMap
}
```
