### ISSUE TITLE
Example / Support for Registering Adapter Factory for External Libraries

### ISSUE THREAD

**Issue by james-novino** [ZacSweers/moshi-sealed#16]
We use Arrow.Core.Option pretty heavily which is essentially a sealed class: 

```
sealed class Option<T> {
        data class Some<T> (val t: T) : Option<T>()
        object None : Option<Nothing>()
    }
```

Cannot add the `@JsonClass(generateAdapter = true, generator = "sealed:type")` to this class since it's defined in an external library. How does this library work in relation to external libraries?

**Comment by ZacSweers** [comment]
You would need to write your own custom adapter
