### ISSUE TITLE
Generate proguard rules on the fly

### ISSUE THREAD

**Issue by ZacSweers** [ZacSweers/moshi-sealed#19]
To match moshi's new behavior

**Comment by tasomaniac** [comment]
Until the proguard rules are created on the fly, what is the recommended proguard rules that needs to be put manually?

**Comment by ZacSweers** [comment]
There are no special rules needed until a new version of Moshi is releases. It inherits whatever Moshi bundles today by depending on it.

**Comment by tasomaniac** [comment]
We had a proguard issue and that's why I found this. It turned out that it was because of the enums we used as properties under the sealed class.

Using `-keepnames` for those enums worked.

**Comment by ZacSweers** [comment]
Per Moshi's rules, enums must be annotated with `@JsonClass(generateAdapter = false)` to be kept
