### ISSUE TITLE
Allow a default class

### ISSUE THREAD

**Issue by casret** [ZacSweers/moshi-sealed#20]
It would be great if the default could be an class instead of an object or null.  The use case around this is sometimes the schema evolves so that it adds a type, and it would be helpful to read old messages into a class.

**Comment by trevjonez** [comment]
Ditto I frequently do something like this as a default.
```kotlin 
class Unknown(val jsonValue: String): Foo()
```

Idea being the data is retained so as types get added even an unknown has enough context to see what came in at a breakpoint or log statement later on.

**Comment by ZacSweers** [comment]
this only works with Moshi's API, which doesn't support these cases. Am I missing something?

**Comment by ZacSweers** [comment]
Closing for now as moshi's polymorphic adapter doesn't support this. We can revisit if that changes
