### ISSUE TITLE
moshi-sealed-reflect depends on SNAPSHOT version of moshi

### ISSUE THREAD

**Issue by edwardaux** [ZacSweers/moshi-sealed#21]
When I first added moshi-sealed-reflect to my gradle file, I go an error complaining that gradle couldn't find `com.squareup.moshi:moshi:1.9.0-SNAPSHOT`

Poking around a bit, I noticed that https://github.com/ZacSweers/moshi-sealed/blob/master/moshi-sealed-reflect/build.gradle is referencing a snapshot version. Is that right?

FWIW, I managed to get past it by changing my app's gradle file to temporarily point moshi to the same SNAPSHOT version and then changed it back 1.9.2. For whatever reason, this is enough to stop gradle complaining.

**Comment by edwardaux** [comment]
Actually, just to clarify my comment about being able to fit it by mucking around with my app's moshi version number... turns out that this works:
```
implementation 'com.squareup.moshi:moshi-adapters:1.9.2'
implementation 'dev.zacsweers.moshisealed:moshi-sealed-annotations:0.1.0'
implementation 'dev.zacsweers.moshisealed:moshi-sealed-reflect:0.1.0'
```

but the following gives me this error ("ERROR: Failed to resolve: com.squareup.moshi:moshi-adapters:1.9.0-SNAPSHOT"):
```
implementation 'com.squareup.moshi:moshi:1.9.2'
implementation 'dev.zacsweers.moshisealed:moshi-sealed-annotations:0.1.0'
implementation 'dev.zacsweers.moshisealed:moshi-sealed-reflect:0.1.0'
```

**Comment by ZacSweers** [comment]
Will fix!

**Comment by ZacSweers** [comment]
Done. Just cut 0.2.0

**Comment by edwardaux** [comment]
Awesome. Thank you.
