### ISSUE TITLE
Use stable Moshi

### ISSUE THREAD

**Issue by ZacSweers** [ZacSweers/moshi-sealed#4]
Once 1.9.0 is released

**Comment by ZacSweers** [comment]
Done!

**Comment by edwardaux** [comment]
I know this is closed, but I just noticed in https://github.com/ZacSweers/moshi-sealed/blob/master/moshi-sealed-reflect/build.gradle that it is still pointing to the SNAPSHOT build. I'm curious if that is on purpose?
